spring:
  application:
    name: financial-manager-v0002
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          format_sql: true

    sql:
      init:
        mode: always
