spring:
  application:
    name: financial-manager-v0002
  data:
    redis:
      host: localhost
      port: 6379


  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver

  jpa:  # ✅ AGORA SIM (fora de datasource)
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

financial:
  bot:
    token: ${FINANCIAL_BOT_TOKEN}
  security:
    jwt:
      token: ${FINANCIAL_JWT_TOKEN}
      issuer: financial-manager